# Generated by Django 4.2.3 on 2026-01-13 03:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('user', 'Users'), ('staffs', 'Staffs')], default='user', help_text='Type of user account', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('other', 'Other')], default='apartment', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo of the property', null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')])),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50, message='Review must be at least 50 characters.')])),
                ('pros_cons', models.TextField(blank=True, help_text='Optional: List pros and cons of the property', max_length=500, null=True)),
                ('date_lived_from', models.DateField(blank=True, help_text='Optional: When did you start living here?', null=True)),
                ('date_lived_to', models.DateField(blank=True, help_text='Optional: When did you stop living here? (leave blank if still living there)', null=True)),
                ('author_name', models.CharField(blank=True, help_text='Optional - leave blank for anonymous', max_length=100)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Comments are automatically approved and visible')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for moderation review')),
                ('flagged_reason', models.TextField(blank=True, help_text='Reason for flagging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this review (for edit/delete permissions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Reply must be at least 10 characters.')])),
                ('author_name', models.CharField(blank=True, help_text='Optional - leave blank for anonymous', max_length=100)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Replies are automatically approved and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_created', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review')),
            ],
            options={
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Professional response to the review', validators=[django.core.validators.MinLengthValidator(20, message='Response must be at least 20 characters.')])),
                ('owner_name', models.CharField(help_text='Name or title of the property owner/manager', max_length=100)),
                ('is_approved', models.BooleanField(default=True, help_text='Responses are automatically approved')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for moderation review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Property owner/landlord who created this response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(help_text='One response per review', on_delete=django.db.models.deletion.CASCADE, related_name='owner_response', to='reviews.review')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('personal_attack', 'Personal Attack or Insult'), ('off_topic', 'Not About the Property'), ('false_information', 'False or Misleading Information'), ('spam', 'Spam or Advertisement'), ('harassment', 'Harassment or Bullying'), ('other', 'Other Violation')], max_length=50)),
                ('description', models.TextField(help_text='Please provide details about why you are reporting this review', max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', related_query_name='resolved_report', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('review', 'reported_by')},
            },
        ),
    ]
