# Generated by Django 4.2.3 on 2026-01-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(blank=True, help_text='Parent reply if this is a reply to a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='reviews.reply'),
        ),
    ]
