# Generated by Django 4.2.3 on 2026-01-22 01:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_customuser_email_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a photo of the property', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Property image', max_length=255, verbose_name='image'),
        ),
    ]
