# Generated by Django 4.2.3 on 2026-01-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Designates whether this user account has been suspended by staff.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the account was suspended.', null=True),
        ),
    ]
