# Generated by Django 4.2.3 on 2026-01-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_add_user_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Describe what happened at this property', null=True),
        ),
    ]
