# Generated by Django 4.2.3 on 2026-01-22 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_add_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(50, message='Review must be at least 50 characters if provided.')]),
        ),
    ]
